### ISSUE TITLE
数据库脚本提供下吧 嘿嘿

### ISSUE THREAD

**Issue by 979943370** [404NotFoundx/microservice#1]
有点懒，嘿嘿

**Comment by 979943370** [comment]
找到了 ~ ~！

**Comment by 404NotFoundx** [comment]
什么脚本呀




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"979943370"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月9日(星期一) 下午2:20
收件人:&nbsp;"404NotFoundx/microservice"<microservice@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [404NotFoundx/microservice] 数据库脚本提供下吧 嘿嘿 (#1)




找到了 ~ ~！

**Comment by 979943370** [comment]
数据库的，已经看到了在 script。 嘿嘿




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"2B键盘"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月9日(星期一) 下午4:47
收件人:&nbsp;"404NotFoundx/microservice"<microservice@noreply.github.com&gt;;
抄送:&nbsp;"979943370"<979943370@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [404NotFoundx/microservice] 数据库脚本提供下吧 嘿嘿 (#1)



什么脚本呀 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"979943370"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2019年12月9日(星期一) 下午2:20 
 收件人:&amp;nbsp;"404NotFoundx/microservice"<microservice@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [404NotFoundx/microservice] 数据库脚本提供下吧 嘿嘿 (#1) 
 
 
 
 
 找到了 ~ ~！

**Comment by 404NotFoundx** [comment]
哦，我知道了，可我现在在公司，数据库在我家笔记本上




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"979943370"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月9日(星期一) 下午2:20
收件人:&nbsp;"404NotFoundx/microservice"<microservice@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [404NotFoundx/microservice] 数据库脚本提供下吧 嘿嘿 (#1)




找到了 ~ ~！

**Comment by 404NotFoundx** [comment]
找到了吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"979943370"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月9日(星期一) 下午4:48
收件人:&nbsp;"404NotFoundx/microservice"<microservice@noreply.github.com&gt;;
抄送:&nbsp;"2B键盘"<spacecloud@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [404NotFoundx/microservice] 数据库脚本提供下吧 嘿嘿 (#1)



数据库的，已经看到了在 script。 嘿嘿 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"2B键盘"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2019年12月9日(星期一) 下午4:47 
 收件人:&amp;nbsp;"404NotFoundx/microservice"<microservice@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"979943370"<979943370@qq.com&amp;gt;;"State change"<state_change@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [404NotFoundx/microservice] 数据库脚本提供下吧 嘿嘿 (#1) 
 
 
 
 什么脚本呀  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"979943370"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2019年12月9日(星期一) 下午2:20  
  收件人:&amp;amp;nbsp;"404NotFoundx/microservice"<microservice@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [404NotFoundx/microservice] 数据库脚本提供下吧 嘿嘿 (#1)  
   
   
   
   
  找到了 ~ ~！

**Comment by 979943370** [comment]
嗯嗯，谢谢老哥




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"2B键盘"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月9日(星期一) 下午4:50
收件人:&nbsp;"404NotFoundx/microservice"<microservice@noreply.github.com&gt;;
抄送:&nbsp;"979943370"<979943370@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [404NotFoundx/microservice] 数据库脚本提供下吧 嘿嘿 (#1)



找到了吗 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"979943370"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2019年12月9日(星期一) 下午4:48 
 收件人:&amp;nbsp;"404NotFoundx/microservice"<microservice@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"2B键盘"<spacecloud@foxmail.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [404NotFoundx/microservice] 数据库脚本提供下吧 嘿嘿 (#1) 
 
 
 
 数据库的，已经看到了在 script。 嘿嘿  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"2B键盘"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2019年12月9日(星期一) 下午4:47  
  收件人:&amp;amp;nbsp;"404NotFoundx/microservice"<microservice@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"979943370"<979943370@qq.com&amp;amp;gt;;"State change"<state_change@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [404NotFoundx/microservice] 数据库脚本提供下吧 嘿嘿 (#1)  
   
   
   
  什么脚本呀   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:&amp;amp;amp;nbsp;"979943370"<notifications@github.com&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2019年12月9日(星期一) 下午2:20   
   收件人:&amp;amp;amp;nbsp;"404NotFoundx/microservice"<microservice@noreply.github.com&amp;amp;amp;gt;;   
   抄送:&amp;amp;amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [404NotFoundx/microservice] 数据库脚本提供下吧 嘿嘿 (#1)   
     
     
     
     
   找到了 ~ ~！

**Comment by 404NotFoundx** [comment]
如果可以的话帮我把github上首页的两个项目点下star把~！
