### ISSUE TITLE
关于你select 标签中写insert

### ISSUE THREAD

**Issue by 979943370** [404NotFoundx/microservice#2]
什么操作，看不懂/😀

**Comment by 404NotFoundx** [comment]
代码看下------------------ 原始邮件 ------------------
发件人: "979943370"<notifications@github.com>
发送时间: 2019年12月9日(星期一) 下午5:08
收件人: "404NotFoundx/microservice"<microservice@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [404NotFoundx/microservice] 关于你select 标签中写insert (#2)



什么操作，看不懂/
 
&mdash;

**Comment by 979943370** [comment]
问文件在那个位置嘛？8001子项目中，resource文件夹中的那个xml，最后一个方法

**Comment by 404NotFoundx** [comment]
没有的话应该是远程配置------------------ 原始邮件 ------------------
发件人: "979943370"<notifications@github.com>
发送时间: 2019年12月10日(星期二) 上午8:32
收件人: "404NotFoundx/microservice"<microservice@noreply.github.com>;
抄送: "2B键盘"<spacecloud@foxmail.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [404NotFoundx/microservice] 关于你select 标签中写insert (#2)



问文&#x4EF6;在那个位置嘛？8001子项目中，resource文&#x4EF6;夹中的那个xml，最后一个方法
 
&mdash;
